// documentation/ag-grid-docs/src/content/docs/aligned-grids/_examples/aligned-grids/provided/modules/angular/app.component.ts
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Component, ViewChild } from '@angular/core';

import { AgGridAngular } from 'ag-grid-angular';
import type { ColDef, ColGroupDef, GridOptions } from 'ag-grid-community';
import { AllCommunityModule, ModuleRegistry } from 'ag-grid-community';

import './styles.css';

ModuleRegistry.registerModules([AllCommunityModule]);

@Component({
    selector: 'my-app',
    standalone: true,
    imports: [AgGridAngular, HttpClientModule],
    template: `
        <div class="test-header" style="height: 5%">
            <label><input type="checkbox" checked (change)="onCbAthlete($event.target.checked)" />Athlete</label>
            <label><input type="checkbox" checked (change)="onCbAge($event.target.checked)" />Age</label>
            <label><input type="checkbox" checked (change)="onCbCountry($event.target.checked)" />Country</label>
        </div>

        <ag-grid-angular
            style="width: 100%; height: 45%"
            #topGrid
            [rowData]="rowData"
            [gridOptions]="topOptions"
            [alignedGrids]="[bottomGrid]"
            [columnDefs]="columnDefs"
        />

        <div style="height: 5%"></div>

        <ag-grid-angular
            style="width: 100%; height: 45%"
            #bottomGrid
            [rowData]="rowData"
            [gridOptions]="bottomOptions"
            [alignedGrids]="[topGrid]"
            [columnDefs]="columnDefs"
        />
    `,
})
export class AppComponent {
    columnDefs!: (ColDef | ColGroupDef)[];
    defaultColDef: ColDef = {
        filter: true,
        minWidth: 100,
    };
    rowData!: any[];
    topOptions: GridOptions = {
        defaultColDef: this.defaultColDef,
        autoSizeStrategy: {
            type: 'fitGridWidth',
        },
    };
    bottomOptions: GridOptions = {
        defaultColDef: this.defaultColDef,
    };

    @ViewChild('topGrid') topGrid!: AgGridAngular;

    constructor(private http: HttpClient) {
        this.columnDefs = [
            { field: 'athlete' },
            { field: 'age' },
            { field: 'country' },
            { field: 'year' },
            { field: 'sport' },
            {
                headerName: 'Medals',
                children: [
                    {
                        columnGroupShow: 'closed',
                        colId: 'total',
                        valueGetter: 'data.gold + data.silver + data.bronze',
                        width: 200,
                    },
                    { columnGroupShow: 'open', field: 'gold', width: 100 },
                    { columnGroupShow: 'open', field: 'silver', width: 100 },
                    { columnGroupShow: 'open', field: 'bronze', width: 100 },
                ],
            },
        ];
    }

    ngOnInit() {
        this.http.get('https://www.ag-grid.com/example-assets/olympic-winners.json').subscribe((data) => {
            this.rowData = data as any[];
        });
    }

    onCbAthlete(value: boolean) {
        // we only need to update one grid, as the other is a slave
        this.topGrid.api.setColumnsVisible(['athlete'], value);
    }

    onCbAge(value: boolean) {
        // we only need to update one grid, as the other is a slave
        this.topGrid.api.setColumnsVisible(['age'], value);
    }

    onCbCountry(value: boolean) {
        // we only need to update one grid, as the other is a slave
        this.topGrid.api.setColumnsVisible(['country'], value);
    }
}

// testing/module-size/src/App.tsx
import { useMemo, useRef, useState } from 'react';

import {
    ColDef,
    ModuleRegistry,
    themeQuartz
} from 'ag-grid-community';

import {
    /** __PLACEHOLDER__START__ */  /** __PLACEHOLDER__END__ */
} from 'ag-grid-community';
import {
    /** __ENTERPRISE_PLACEHOLDER__START__ */  /** __ENTERPRISE_PLACEHOLDER__END__ */
} from 'ag-grid-enterprise';
import { AgGridReact } from 'ag-grid-react';

ModuleRegistry.registerModules([
    /** __PLACEHOLDER__START__ */  /** __PLACEHOLDER__END__ */
]);

ModuleRegistry.registerModules([
    /** __ENTERPRISE_PLACEHOLDER__START__ */  /** __ENTERPRISE_PLACEHOLDER__END__ */
]);

export const App = () => {
    const gridRef = useRef<AgGridReact>(null);
    const containerStyle = useMemo(() => ({ width: '100%', height: '100%' }), []);
    const gridStyle = useMemo(() => ({ height: '100%', width: '100%' }), []);
    const [rowData, setRowData] = useState<any[]>();
    const [columnDefs] = useState<ColDef[]>([
        {
            field: 'athlete',
            minWidth: 150,
        },
        { field: 'age', maxWidth: 90 },
        { field: 'country', minWidth: 150 },
        { field: 'year', maxWidth: 90 },
        { field: 'date', minWidth: 150 },
        { field: 'sport', minWidth: 150 },
        { field: 'gold' },
        { field: 'silver' },
        { field: 'bronze' },
        { field: 'total' },
    ]);
    const defaultColDef = useMemo<ColDef>(() => {
        return {
            flex: 1,
            minWidth: 100,
            filter: true,
        };
    }, []);

    const onGridReady = () => {
        fetch('https://www.ag-grid.com/example-assets/olympic-winners.json')
            .then((resp) => resp.json())
            .then((data) => setRowData(data));
    };

    return (
        <div style={containerStyle}>
            <div className="example-wrapper">
                <div style={gridStyle} className={'ag-theme-quartz-dark'}>
                    <AgGridReact
                        ref={gridRef}
                        theme={themeQuartz}
                        rowData={rowData}
                        columnDefs={columnDefs}
                        defaultColDef={defaultColDef}
                        onGridReady={onGridReady}
                    />
                </div>
            </div>
        </div>
    );
};
